### ISSUE TITLE
Not working with logback AsyncAppender

### ISSUE THREAD

**Issue by halber** [reactiverse/reactiverse-contextual-logging#42]
It doesn't work with the logback async appender because the log message is created in a non Vert.x thread and calling Vertx.currentContext() in [LogbackConverter](https://github.com/reactiverse/reactiverse-contextual-logging/blob/39e691d3a8fd78d19ee120cab8d8b38a4ef67813/src/main/java/io/reactiverse/contextual/logging/LogbackConverter.java#L55) always returns null in this case.

example logback configuration to reproduce the issue:
```xml
<configuration debug="false">
    <conversionRule conversionWord="vcl" converterClass="io.reactiverse.contextual.logging.LogbackConverter"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%vcl{requestId:-foobar} ### %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="ASYNC_STDOUT" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="STDOUT" />
    </appender>

    <root level="DEBUG">
        <appender-ref ref="ASYNC_STDOUT"/>
    </root>

</configuration>
```

**Comment by tsegismont** [comment]
Yes, this is a limitation of the converter approach. However, I'm not sure how we can proceed because Logback does not provide a plugin mechanism for providing context when the logging event is created.

As a workaround, you could keep the slf4j API in your code but switch to log4j2.

Check out the documentation for integration with our [context data provider](https://reactiverse.io/reactiverse-contextual-logging/#log4j2_context_data_provider)
